name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"   # se ejecuta cada d√≠a
  workflow_dispatch:      # permite ejecutarlo manualmente

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: Matthrve
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#7F3ACE

      - name: Publish snake animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
